nyaa script turns out zsh doesn't have integer arrays, or i don't know how to use em nyaa fixes, sorting added scihub small improvement     ${scalar}${^array} & ${^array}${^array} produce all permutations - nice libgen small fixes, mirrors kinda fixed libgen standard mirrors fixed audiobookbay small fix libgen mirror fix rtorrent support for torrenting scripts difference between return and exit... iregex - interective perl one-liners ... ........................

diff --git a/src/sfeed/README b/src/sfeed/README
--- a/src/sfeed/README
+++ b/src/sfeed/README
@@ -111,7 +111,7 @@ Optional dependencies
 OS tested
 ---------
 
-- Linux (compilers: clang, gcc, pcc, tcc, libc: glibc, musl).
+- Linux (compilers: clang, cproc, gcc, lacc, pcc, tcc, libc: glibc, musl).
 - OpenBSD (clang, gcc).
 - NetBSD
 - FreeBSD
@@ -119,12 +119,13 @@ OS tested
 - Windows (cygwin gcc, mingw).
 - HaikuOS (using libbsd).
 - FreeDOS (djgpp).
+- FUZIX (sdcc -mz80).
 
 
 Architectures tested
 --------------------
 
-amd64, ARM, aarch64, HPPA, i386, SPARC64.
+amd64, ARM, aarch64, HPPA, i386, MIPS32-BE, SPARC64, Z80.
 
 
 Files
@@ -142,7 +143,7 @@ sfeed_mbox        - Format feed data (TSV) to mbox.
 sfeed_plain       - Format feed data (TSV) to a plain-text list.
 sfeed_twtxt       - Format feed data (TSV) to a twtxt feed.
 sfeed_update      - Update feeds and merge items.
-sfeed_web         - Find urls to RSS/Atom feed from a webpage.
+sfeed_web         - Find URLs to RSS/Atom feed from a webpage.
 sfeed_xmlenc      - Detect character-set encoding from a XML stream.
 sfeedrc.example   - Example config file. Can be copied to $HOME/.sfeed/sfeedrc.
 style.css         - Example stylesheet to use with sfeed_html(1) and
@@ -155,7 +156,7 @@ Files read at runtime by sfeed_update(1)
 sfeedrc - Config file. This file is evaluated as a shellscript in
           sfeed_update(1).
 
-Atleast the following functions can be overridden per feed:
+At least the following functions can be overridden per feed:
 
 - fetch: to use wget(1), OpenBSD ftp(1) or an other download program.
 - filter: to filter on fields.
@@ -189,7 +190,7 @@ man 1 sfeed
 Usage and examples
 ------------------
 
-Find RSS/Atom feed urls from a webpage:
+Find RSS/Atom feed URLs from a webpage:
 
 	url="https://codemadness.org"; curl -L -s "$url" | sfeed_web "$url"
 
@@ -225,7 +226,7 @@ View formatted output in your editor:
 - - -
 
 Example script to view feed items in a vertical list/menu in dmenu(1). It opens
-the selected url in the browser set in $BROWSER:
+the selected URL in the browser set in $BROWSER:
 
 	#!/bin/sh
 	url=$(sfeed_plain "$HOME/.sfeed/feeds/"* | dmenu -l 35 -i | \
@@ -251,7 +252,7 @@ argument is optional):
 - - -
 
 The filter function can be overridden in your sfeedrc file. This allows
-filtering items per feed. It can be used to shorten urls, filter away
+filtering items per feed. It can be used to shorten URLs, filter away
 advertisements, strip tracking parameters and more.
 
 	# filter fields.
@@ -288,14 +289,14 @@ advertisements, strip tracking parameters and more.
 				}
 
 				# shorten feedburner links.
-				if (match(s, /^(http|https):\/\/[^/]+\/~r\/.*\/~3\/[^\/]+\//)) {
+				if (match(s, /^(http|https):\/\/[^\/]+\/~r\/.*\/~3\/[^\/]+\//)) {
 					s = substr($3, RSTART, RLENGTH);
 				}
 
 				# strip tracking parameters
 				# urchin, facebook, piwik, webtrekk and generic.
-				gsub(/\?(ad|campaign|pk|tm|wt)_([^&]+)/, "?", s);
-				gsub(/&(ad|campaign|pk|tm|wt)_([^&]+)/, "", s);
+				gsub(/\?(ad|campaign|fbclid|pk|tm|utm|wt)_([^&]+)/, "?", s);
+				gsub(/&(ad|campaign|fbclid|pk|tm|utm|wt)_([^&]+)/, "", s);
 
 				gsub(/\?&/, "?", s);
 				gsub(/[\?&]+$/, "", s);
@@ -311,18 +312,6 @@ advertisements, strip tracking parameters and more.
 
 				print $0;
 			}'
-	}
-
-- - -
-
-The fetch function can be overridden in your sfeedrc file. This allows to
-replace the default curl(1) for sfeed_update with any other client to fetch the
-RSS/Atom data:
-
-	# fetch a feed via HTTP/HTTPS etc.
-	# fetch(name, url, feedfile)
-	fetch() {
-		hurl -m 1048576 -t 15 "$2" 2>/dev/null
 	}
 
 - - -
@@ -378,7 +367,7 @@ cut -b is used to trim the "N " prefix of sfeed_plain(1).
 - - -
 
 For some podcast feed the following code can be used to filter the latest
-enclosure url (probably some audio file):
+enclosure URL (probably some audio file):
 
 	awk -F '\t' 'BEGIN { latest = 0; }
 	length($8) {
@@ -551,28 +540,59 @@ Now you can view feeds in mutt(1) for example.
 
 - - -
 
-Incremental data updates
+The fetch function can be overridden in your sfeedrc file. This allows to
+replace the default curl(1) for sfeed_update with any other client to fetch the
+RSS/Atom data or change the default curl options:
 
-For servers that support it some incremental updates and bandwidth-saving can
-be done by using the "If-Modified-Since" HTTP header.
-
-The curl -z option can be used to send the modification date of the local feed
-file so the server can make the decision to respond with incremental data.
-
-You can do this by overriding the fetch() function in the sfeedrc file and
-adding the -z option:
-
+	# fetch a feed via HTTP/HTTPS etc.
 	# fetch(name, url, feedfile)
 	fetch() {
-		curl -z "$3" "$2"
+		hurl -m 1048576 -t 15 "$2" 2>/dev/null
 	}
-
-This comes at a cost of some privacy. For example there can be a fingerprinting
-vector of the local modification date of the feed file.
 
 - - -
 
-CDN's blocking requests due to missing User-Agent
+Caching, incremental data updates and bandwidth-saving
+
+For servers that support it some incremental updates and bandwidth-saving can
+be done by using the "ETag" HTTP header.
+
+Create a directory for storing the ETags per feed:
+
+	mkdir -p ~/.sfeed/etags/
+
+The curl ETag options (--etag-save and --etag-compare) can be used to store and
+send the previous ETag header value. curl version 7.73+ is recommended for it
+to work properly.
+
+The curl -z option can be used to send the modification date of a local file as
+a HTTP "If-Modified-Since" request header. The server can then respond if the
+data is modified or not or respond with only the incremental data.
+
+The curl --compressed option can be used to indicate the client supports
+decompression. Because RSS/Atom feeds are textual XML content this generally
+compresses very well.
+
+These options can be set by overriding the fetch() function in the sfeedrc
+file:
+
+	# fetch(name, url, feedfile)
+	fetch() {
+		etag="$HOME/.sfeed/etags/$(basename "$3")"
+		curl \
+			-L --max-redirs 0 -H "User-Agent:" -f -s -m 15 \
+			--compressed \
+			--etag-save "${etag}" --etag-compare "${etag}" \
+			-z "${etag}" \
+			"$2" 2>/dev/null
+	}
+
+These options can come at a cost of some privacy, because it exposes
+additional metadata from the previous request.
+
+- - -
+
+CDNs blocking requests due to a missing HTTP User-Agent request header
 
 sfeed_update will not send the "User-Agent" header by default for privacy
 reasons.  Some CDNs like Cloudflare don't like this and will block such HTTP
@@ -587,12 +607,78 @@ Firefox 78.
 
 - - -
 
+Page redirects
+
+For security and efficiency reasons by default redirects are not allowed and
+are treated as an error.
+
+For example to prevent hijacking an unencrypted http:// to https:// redirect or
+to not add time of an unnecessary page redirect each time.  It is encouraged to
+use the final redirected URL in the sfeedrc config file.
+
+If you want to ignore this advise you can override the fetch() function in the
+sfeedrc file and change the curl options "-L --max-redirs 0".
+
+- - -
+
+Shellscript to update feeds in parallel more efficiently using xargs -P.
+
+It creates a queue of the feeds with its settings, then uses xargs to process
+them in parallel using the common, but non-POSIX -P option. This is more
+efficient than the more portable solution in sfeed_update which can stall a
+batch of $maxjobs in the queue if one item is slow.
+
+sfeed_update_xargs shellscript:
+
+	#!/bin/sh
+	# update feeds, merge with old feeds using xargs in parallel mode (non-POSIX).
+	
+	# include script and reuse its functions, but do not start main().
+	SFEED_UPDATE_INCLUDE="1" . sfeed_update
+	# load config file, sets $config.
+	loadconfig "$1"
+	
+	# process a single feed.
+	# args are: config, tmpdir, name, feedurl, basesiteurl, encoding
+	if [ "${SFEED_UPDATE_CHILD}" = "1" ]; then
+		sfeedtmpdir="$2"
+		_feed "$3" "$4" "$5" "$6"
+		exit $?
+	fi
+	
+	# ...else parent mode:
+	
+	# feed(name, feedurl, basesiteurl, encoding)
+	feed() {
+		# workaround: *BSD xargs doesn't handle empty fields in the middle.
+		name="${1:-$$}"
+		feedurl="${2:-http://}"
+		basesiteurl="${3:-${feedurl}}"
+		encoding="$4"
+	
+		printf '%s\0%s\0%s\0%s\0%s\0%s\0' "${config}" "${sfeedtmpdir}" \
+			"${name}" "${feedurl}" "${basesiteurl}" "${encoding}"
+	}
+	
+	# fetch feeds and store in temporary directory.
+	sfeedtmpdir="$(mktemp -d '/tmp/sfeed_XXXXXX')"
+	# make sure path exists.
+	mkdir -p "${sfeedpath}"
+	# print feeds for parallel processing with xargs.
+	feeds | SFEED_UPDATE_CHILD="1" xargs -r -0 -P "${maxjobs}" -L 6 "$(readlink -f "$0")"
+	# cleanup temporary files etc.
+	cleanup
+
+- - -
+
 Shellscript to export existing newsboat cached items from sqlite3 to the sfeed
 TSV format.
-	
+
 	#!/bin/sh
 	# Export newsbeuter/newsboat cached items from sqlite3 to the sfeed TSV format.
 	# The data is split per file per feed with the name of the newsboat title/url.
+	# It writes the URLs of the read items line by line to a "urls" file.
+	#
 	# Dependencies: sqlite3, awk.
 	#
 	# Usage: create some directory to store the feeds, run this script.
@@ -614,8 +700,8 @@ TSV format.
 	SELECT
 		i.pubDate, i.title, i.url, i.content, i.guid, i.author,
 		i.enclosure_url,
-		f.rssurl AS rssurl, f.title AS feedtitle --,
-		-- i.id, i.unread, i.enclosure_type, i.enqueued, i.flags, i.deleted,
+		f.rssurl AS rssurl, f.title AS feedtitle, i.unread --,
+		-- i.id, i.enclosure_type, i.enqueued, i.flags, i.deleted,
 		-- i.base
 	FROM rss_feed f
 	INNER JOIN rss_item i ON i.feedurl = f.rssurl
@@ -629,13 +715,19 @@ TSV format.
 		FS = "\x1f";
 		RS = "\x1e";
 	}
-	# strip all control-chars for normal fields.
-	function strip(s) {
+	# normal non-content fields.
+	function field(s) {
+		gsub("^[[:space:]]*", "", s);
+		gsub("[[:space:]]*$", "", s);
+		gsub("[[:space:]]", " ", s);
 		gsub("[[:cntrl:]]", "", s);
 		return s;
 	}
-	# escape chars in content field.
-	function escape(s) {
+	# content field.
+	function content(s) {
+		gsub("^[[:space:]]*", "", s);
+		gsub("[[:space:]]*$", "", s);
+		# escape chars in content field.
 		gsub("\\\\", "\\\\", s);
 		gsub("\n", "\\n", s);
 		gsub("\t", "\\t", s);
@@ -651,9 +743,14 @@ TSV format.
 			print "Writing file: \"" fname "\" (title: " $9 ", url: " $8 ")" > "/dev/stderr";
 		}
 	
-		print $1 "\t" strip($2) "\t" strip($3) "\t" escape($4) "\t" \
-			"html" "\t" strip($5) "\t" strip($6) "\t" strip($7) \
+		print $1 "\t" field($2) "\t" field($3) "\t" content($4) "\t" \
+			"html" "\t" field($5) "\t" field($6) "\t" field($7) \
 			> fname;
+	
+		# write URLs of the read items to a file line by line.
+		if ($10 == "0") {
+			print $3 > "urls";
+		}
 	}'
 
 
